spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.55.48:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  #redis集群版
  redis:
    timeout: 6000ms
    database: 0
    cluster:
      nodes:
        - 172.16.55.39:7001
        - 172.16.55.39:7002
        - 172.16.55.39:7003
        - 172.16.55.39:7004
        - 172.16.55.39:7005
        - 172.16.55.39:7006
      max-redirects: 3 # 获取失败 最大重定向次数
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

